apiVersion: apps/v1
kind: Deployment
metadata:
  name: consommateur
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: apache
        image: httpd:2.4-alpine
        volumeMounts:
        - name: data
          mountPath: /htdocs
      volumes:
      - name: data
        hostPath:
          path: /tmp
